apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  upstreamNameservers: |
    ["192.168.143.153"]
---
apiVersion: v1
kind: Service
metadata:
  name: aced-dns
  namespace: default
spec:
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    app: aced-dns
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aced-dns
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: aced-dns
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: aced-dns-container
        image: quay.cnqr.delivery/containerhosting/aced-dns
        volumeMounts:
        - name: shared-data
          mountPath: /shared-data
        command: ["aced-dns"]
        args: ["-logtostderr", "-outputdir", "/shared-data"]
      - name: named-container
        image: quay.cnqr.delivery/containerhosting/aced-dns
        volumeMounts:
        - name: shared-data
          mountPath: /shared-data
        command: ["named"]
        args: ["-g"]
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
