apiVersion: v1
kind: Service
metadata:
  name: mynginx1
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: mynginx1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mynginx1
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        concur.com/aced-nameserver: 10.10.10.10
        concur.com/aced-environment: foo
      labels:
        app: mynginx1
    spec:
      containers:
      - image: nginx
        name: mynginx1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx2
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: mynginx2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mynginx2
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        concur.com/aced-nameserver: 20.20.20.20
        concur.com/aced-environment: bar
      labels:
        app: mynginx2
    spec:
      containers:
      - image: nginx
        name: mynginx2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx3
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: mynginx3
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mynginx3
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        concur.com/aced-nameserver: 30.30.30.30
        concur.com/aced-environment: baz
      labels:
        app: mynginx3
    spec:
      containers:
      - image: nginx
        name: mynginx3
        ports:
        - containerPort: 80
