apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: named-container
    image: custom-dns
    volumeMounts:
    - name: shared-data
      mountPath: /shared-data
    command: ["named"]
    args: ["-g"]
  - name: rndc-container
    image: custom-dns
    volumeMounts:
    - name: shared-data
      mountPath: /shared-data
    command: ["rndc"]
    args: ["status"]
